spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sbDemo

mybatis:
  mapper-locations: "classpath:/MyBatis/mapper/*.xml"
